logging:
  level:
    reactor:
      netty: DEBUG
    org:
      springframework:
        web:
          reactive: TRACE
          boot:
            autoconfigure:
              web: TRACE
        cloud:
          gateway: TRACE
        http:
          server:
            reactive: TRACE
management:
  endpoints:
    web:
      exposure:
        include: "*"
gateway:
  fallback:
    enabled: true
    httpUrl: http://localhost
    port: 8282
spring:
  cloud:
    gateway:
      routes:
        - id: accounts
          uri: ${SERVER_URI_1:http://localhost:8181}
          predicates:
            - Path=/accounts/**
          filters:
            #            - PrefixPath=/accounts
            #            - StripPrefix=1
            #            - name: CircuitBreaker
            #              args:
            #                name: myCircuitBreaker
            #                fallbackUri: forward:/inCaseOfFailureUseThis
            - name: CircuitBreaker
              args:
                name: failBackCircuitBreaker
                fallbackUri: forward:/fallback
                statusCodes:
                  - 610
                  - 500
                  - "NOT_FOUND"